### ISSUE TITLE
Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by JohnTan38** [RishiBakshii/mern-ecommerce#2]
demo@gmail.com
helloWorld@123

thank you for excellent App. there're issues.
login credentials not working. error message: Cannot read properties of undefined (reading 'data')
please assist to resolve. thank you

**Comment by JohnTan38** [comment]
const express = require("express");
const app = express();
const mongoose = require("mongoose");
const dotenv = require("dotenv");
dotenv.config();
const userRoute = require("./routes/user");
const authRoute = require("./routes/auth");
const productRoute = require("./routes/product");
const cartRoute = require("./routes/cart");
const orderRoute = require("./routes/order");
const stripeRoute = require("./routes/stripe");
const cors = require("cors");


mongoose
  .connect(process.env.MONGO_URL)
  .then(() => console.log("DB Connection Successfull!"))
  .catch((err) => {
    console.log(err);
  });

app.use(cors());
app.use(express.json());
app.use("/api/auth", authRoute);
app.use("/api/users", userRoute);
app.use("/api/products", productRoute);
app.use("/api/carts", cartRoute);
app.use("/api/orders", orderRoute);
app.use("/api/checkout", stripeRoute);

app.listen(process.env.PORT || 5000, () => {
  console.log("Backend server is running!");
});

I'm a Javascript newbie (more well versed in Python). Look forward to this great working App. Thank you!

**Comment by Swathi-demo** [comment]
@RishiBakshii @JohnTan38 thank you for excellent App. there're issues.
login credentials not working. 
please assist to resolve. thank you

**Comment by gajeraharsh** [comment]
i solved this issue by add this code

`server.use(
  cors({
    credentials: true,
    origin:process.env.ORIGIN,
    exposedHeaders: ["X-Total-Count"],
    methods: ["GET", "POST", "PATCH", "DELETE"],
  })
);
`

**Comment by RishiBakshii** [comment]
@gajeraharsh that's great man! can you raise a pull request? i will merge your changes asap

**Comment by gajeraharsh** [comment]
@RishiBakshii , I have raised a pull request. Please review it at your earliest convenience and merge it if everything looks good. Thank you!

**Comment by RishiBakshii** [comment]
hi @gajeraharsh i have merged your pull request. Thankyou so much for your contribution in this repo. I futher insist you to please checkout my latest project https://baatchit.online it's a realtime end-end-encrypted chat application and it is also open source
here the repo link -> https://github.com/RishiBakshii/Baatchit-Modern-Chat-Application

**Comment by JohnTan38** [comment]
Thank you sir Sent from my iPhoneOn 28 Jul 2024, at 2:28 PM, Gajera Harsh ***@***.***> wrote:﻿
i solved this issue by add this code
server.use( cors({ credentials: true, origin:process.env.ORIGIN, exposedHeaders: ["X-Total-Count"], methods: ["GET", "POST", "PATCH", "DELETE"], }) );

**Comment by keyurdevani289** [comment]
![image](https://github.com/user-attachments/assets/2490d186-9ea1-4ed0-86ed-106fc0e76bc6)
![image](https://github.com/user-attachments/assets/b3b6c69f-82d4-4fee-9db4-2e7c2db093a8)
i am still getting cors error can you please check it i have cloned your latest code @RishiBakshii
